services:
  kara-bank:
    build:
      context: ./cmd
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "8080:8080"
      - "9090:9090"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      REST_SERVER_PORT: ":8080"
      GRPC_SERVER_PORT: ":9090"
      DB_CONNECTION: "postgres://postgres:postgres@host.docker.internal:5433/kara_bank_db?sslmode=disable&pool_max_conns=10"

  postgres:
    container_name: postgres
    image: 'postgres:16.3-alpine'
    ports:
      - "5433:5432"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "kara_bank_db"
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data
      - ./db-script/init.sql:/docker-entrypoint-initdb.d/public_schema.sql