services:
  postgres:
    container_name: postgres
    image: 'postgres:16.3-alpine'
    ports:
      - "5433:5432"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "kara_bank_db"
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data